language: java
sudo: false

jdk:
  - openjdk7
  - oraclejdk7  
  - oraclejdk8

env:
  - ARGS="site -Dlinkcheck.skip=true -Dmaven.javadoc.skip=true"
  - ARGS="-Dpmd.skip=true -Dfindbugs.skip=true"
  
install: mvn clean verify $ARGS
#site -Dlinkcheck.skip=true -Dmaven.javadoc.skip=true
#             -Dpmd.skip=true -Dfindbugs.skip=true

after_success:
  - mvn clean cobertura:cobertura coveralls:report
  
cache:
  directories:
  - ~/.m2

branches:
  only:
    - master

matrix:
  fast_finish: true
