language: java
sudo: false

jdk:
  - openjdk7
  - oraclejdk7  
  - oraclejdk8

env:
  - ARGS="test"
  # cobertura validation
  - ARGS="verify -Dpmd.skip=true -Dfindbugs.skip=true"
  # checkstyle
  - ARGS="verify -DskipTests -Dpmd.skip=true -Dfindbugs.skip=true -Dcobertura.skip=true"
  # findbugs + pmd
  - ARGS="compile pmd:check findbugs:check"
  # full site
  - ARGS="site -Dlinkcheck.skip=true -Dmaven.javadoc.skip=true -DskipTests -Dpmd.skip=true -Dfindbugs.skip=true -Dcobertura.skip=true"

  
install: mvn clean $ARGS
#site -Dlinkcheck.skip=true -Dmaven.javadoc.skip=true
#             -Dpmd.skip=true -Dfindbugs.skip=true

after_success:
  - mvn clean cobertura:cobertura coveralls:report
  
cache:
  directories:
  - ~/.m2

branches:
  only:
    - master

matrix:
  fast_finish: true
