language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7  
  - oraclejdk8
  
install: mvn clean verify site

after_success:
  - mvn -Ptravis surefire-report:report jacoco:report coveralls:jacoco

